### PR TITLE
Typedefinitions for the use with typescript

### PR DESCRIPTION
**Pull request by kaoDev**
with this declaration file the micro lib can be used with typescript.

### CODE REVIEW

**Comment by leo** [comment]
Thank you for your effort on this! But please ask the team regarding such additions before you start working on them. In this case, for example, @zeit is not using TypeScript at all, which means that we won't be able to maintain this code. In addition, we don't have any plans on using it anywhere.

I hope you understand... 🙈

**Comment by floatdrop** [comment]
@kaoDev you can add these to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead, which is more preferred way to add typing to node modules.

**Comment by kaoDev** [comment]
@floatdrop the next stop will be the DefinitelyTyped repo, although I think the better way and also preferred way is to have the typings directly in the npm lib instead of having to install another dependency from the @types namespace.

@leo I wrote this definitions at first for my own TypeScript project, so the work was done anyway.

**Comment by ythecombinator** [comment]
Hey @kaoDev! Thanks for your effort; I'm very interested in using your definitions but couldn't find them on DefinitelyTyped. Any plans?

**Comment by kaoDev** [comment]
@ythecombinator sorry for the wait, I had just too much to do the last days. I will push an hour of opensource in today :)

**Pull request closed without merging**
