### PR TITLE
Fix initial example and commas in readme

### LINKED ISSUE #213: Can't set headers after they are sent.
I was trying micro again, starting with the simplest readme examples.

This works, no errors or warning:
```
module.exports = () => 'Welcome to micro'
```

But I'm getting an unhandled rejection error when I hit localhost:3000 but I get the expected response in the browser::
```
module.exports = (req, res) => res.end('Welcome to micro')
```

The full error is:
```
Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at send (/home/millette/tim/node_modules/micro/lib/server.js:134:7)
    at sendError (/home/millette/tim/node_modules/micro/lib/server.js:144:5)
    at Promise.then.catch.err (/home/millette/tim/node_modules/micro/lib/server.js:36:19)
    at tryCatcher (/home/millette/tim/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/millette/tim/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/millette/tim/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/millette/tim/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/millette/tim/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/millette/tim/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/millette/tim/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/millette/tim/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Finally, I got his working, no errors:

```
// npm
const send = require('micro').send

module.exports = (req, res) => send(res, 200, 'Welcome to micro')
```

### PR DESCRIPTION
**Pull request by floatdrop**
Fixes #213

### CODE REVIEW

**Comment by leo** [comment]
No semicolons, please! The only reason why we have them at the moment is prettier. But they'll soon add an option for disabling them again!

**Comment by floatdrop** [comment]
@leo I thought it was on purpose 🤔

**Comment by leo** [comment]
No 😊 Thanks!

**Comment by millette** [comment]
Thanks!

**Pull request merged**
