### PR TITLE
Listen to process.env.PORT || 3000

### PR DESCRIPTION
**Pull request by brunolemos**
Fix heroku support.

### CODE REVIEW

**Review by sergiodxa — APPROVED** [review]

**Review by styfle — APPROVED** [review]

**Comment by timneutkens** [comment]
Can't you just do `micro -l $PORT` 🤔

**Comment by timneutkens** [comment]
Essentially the same PR we closed because of the same reason: https://github.com/zeit/micro/pull/120

**Comment by brunolemos** [comment]
> Can't you just do micro -l $PORT

No, got this error on heroku when using `micro -l $PORT`: 
`Invalid URL: 25103`

This works: `micro -l tcp://0.0.0.0:$PORT`
But it's not ideal IMO, it should just work. It's such a simple thing.

**Comment by timneutkens** [comment]
It's non-standard behavior from Heroku's side, so it shouldn't "just work", instead we should document to use `micro -l tcp://0.0.0.0:$PORT` which we did before in the readme, but it was lost somewhere, I guess when `-p` was replaced with `-l`.

**Review by notrab — APPROVED** [review]

**Comment by sunsean** [comment]
Does adding default detection of `$PORT` cause any problems?
Currently [cross-env-shell](https://www.npmjs.com/package/cross-env) or similar is required to write a run command that runs cross-os.

**Review by sunsean — APPROVED** [review]

**Comment by timneutkens** [comment]
I'm going to close this PR as per my earlier comment. It's unexpected behavior + potentially breaking if `PORT` is defined in the current environment.

**Pull request closed without merging**
