### PR TITLE
Allow async-to-gen register to be loaded more than once

### PR DESCRIPTION
**Pull request by timneutkens**
@leo as we talked about.

### CODE REVIEW

**Comment by timneutkens** [comment]
@leebyron 
Hi Lee, `async-to-gen/register` registers the require hook at the moment you call `require('async-to-gen/register')` instead of when calling the exported function. Because of this you can't use it twice with different configs. Is there any reasoning behind this we haven't thought of?

**Comment by leebyron** [comment]
The require hook has a global effect on the environment, so a second call with a different configuration would overwrite the first.

Since the require hook is a development-time aid for what will ultimately be the configuration to the transform script, I thought it would be too confusing (or a possible "foot gun") to suggest the config be overwritten at runtime

**Comment by timneutkens** [comment]
@leebyron yeah it would introduce some unwanted effects when used improperly, so I guess it's best for most use cases 😄

**Comment by leo** [comment]
Fixed! Thanks guys 😊

**Pull request closed without merging**
