### PR TITLE
remove unused argument for sendError

### LINKED ISSUE #343: Why req arg is required in sendError function
`type sendError = (req, res, errorObj) => void`

The function not read any values from `req`.

### PR DESCRIPTION
**Pull request by maxbeatty**
fixes #343 

feels too simple. what is being overlooked?

### CODE REVIEW

**Comment by timneutkens** [comment]
It's breaking / backwards incompatible right 🤔

**Comment by maxbeatty** [comment]
absolutely. are you trying to keep everything backwards compatible? if not, is there a v10 milestone/timeline?

**Comment by timneutkens** [comment]
As far as I'm aware this would indeed be a case where we wanted it to be backwards compatible as there are a massive amount of microservices out there that use micro. Even counting in ZEIT alone.

**Comment by maxbeatty** [comment]
No worries. Completely understand. Should this and #343 be closed then?

**Comment by timneutkens** [comment]
Thanks @maxbeatty 🙏 I've closed the issue.

**Pull request closed without merging**
