### PR TITLE
ci: `.yml` file should be written in proper `.yml` syntax

### PR DESCRIPTION
**Pull request by luftywiranda13**
Make `.yml` really `.yml` 😬
It was json, right?

### CODE REVIEW

**Comment by timneutkens** [comment]
I believe this was intentional by @leo 🤔

**Comment by leo** [comment]
YAML is a superset of JSON 😊 This is a JS project, so we need to use the JavaScriptObjectNationSyntax.

**Comment by luftywiranda13** [comment]
what's wrong with using proper YAML, btw?
or is there any particular reason you stick using json in .yml? 🤔

**Comment by leo** [comment]
@luftywiranda13 Travis CI doesn't support .json 😊

**Comment by dimapaloskin** [comment]
@leo I guess @luftywiranda13 mean other stuff.
It's concerns file extension and their contents.
So when you make something like:
```
cat ./.travis.yml
``` 
you expect to see yaml syntax :)

**Pull request closed without merging**
