### PR TITLE
Add watch functionality

### PR DESCRIPTION
**Pull request by joshbetz**
Watch the source directory and automatically reload when changes are made.

### CODE REVIEW

**Comment by rauchg** [comment]
cool! need to take a better look but this seems awesome

**Comment by joshbetz** [comment]
Yeah, this was a quick first pass. Need to make sure the require cache isn't going to cause any problems, at least.

**Comment by onbjerg** [comment]
Any updates on this? It's been a few months 😄

**Comment by leo** [comment]
@joshbetz Can you please update the PR? 😊

**Pull request closed without merging**
