### PR TITLE
Added support for abstract streams

### PR DESCRIPTION
**Pull request by mikeal**
An instanceof check alone isn't quite enough for stream validation because it could also be an abstract stream conforming to the readable stream API.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Interesting! Looks 👌

**Comment by leo** [comment]
@mikeal Looks wonderful! 😊 

Would you mind adding a test for this so that our coverage stays at 100%?

**Comment by floatdrop** [comment]
@leo @timneutkens maybe it is better to pick up [is-stream](https://github.com/sindresorhus/is-stream) module for this?

**Comment by leo** [comment]
Now taking advantage of `is-stream`. 🚀 

Released in [8.0.4](https://github.com/zeit/micro/releases/tag/8.0.4). Thank you, @mikeal! ❤️

**Pull request merged**
